FROM node:20-alpine

WORKDIR /app

# Hardcoded backend URL
ENV REACT_APP_BACKEND_URL=https://api.shieldfoundation.in/

# Install dependencies
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy source code
COPY frontend/ ./

# Fix CRACO permission
RUN chmod +x node_modules/.bin/craco

# Build React app
RUN yarn build

# Install lightweight server
RUN yarn global add serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
